GET http://localhost:5000/user
Authorization: Bearer 

###
POST http://localhost:5000/user
Content-Type: application/json 

{
    "username": "adminkyut123", 
    "password": "12345"  
}

###
POST http://localhost:5000/login
Content-Type: application/json 

{
    "username": "adminkyut123", 
    "password": "12345"  
}

###
POST http://localhost:5000/daftarpemilik
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbmt5dXQxMjMiLCJpYXQiOjE3NDgyMjkyNTYsImV4cCI6MTc0ODIzMDE1Nn0.JVQzhroNHf-nBFBpmmDNyRkgWjunSitRO3upk1UG6kA

{
    "nama_pemilik": "kartika", 
    "no_hp": "0888100200", 
    "alamat": "janti", 
    "email": "karkar@gmail.com"
}

###
POST http://localhost:5000/daftarpemilik
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbmt5dXQxMjMiLCJpYXQiOjE3NDgyMjkyNTYsImV4cCI6MTc0ODIzMDE1Nn0.JVQzhroNHf-nBFBpmmDNyRkgWjunSitRO3upk1UG6kA

{
    "nama_pemilik": "difa", 
    "no_hp": "012345678", 
    "alamat": "sewon", 
    "email": "dipadipu@gmail.com"
}

###
POST http://localhost:5000/daftarhewan
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbmt5dXQxMjMiLCJpYXQiOjE3NDgyMjg5NjQsImV4cCI6MTc0ODIyOTg2NH0.q5XP-0FHKUGppU4Z-x3U5S2Y213aKgh65HI6rXDLg4Q

{
    "nama_hewan": "cici", 
    "bobot_hewan": 3, 
    "keterangan_khusus": "harus pakai treat", 
    "ras": "kucing siamese", 
    "gambar": "",
    "pemilikId": 1
}

###
PUT http://localhost:5000/daftarhewan/1
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbmt5dXQxMjMiLCJpYXQiOjE3NDgyMjg5NjQsImV4cCI6MTc0ODIyOTg2NH0.q5XP-0FHKUGppU4Z-x3U5S2Y213aKgh65HI6rXDLg4Q 

{
    "nama_hewan": "si imhut", 
    "bobot_hewan": 15, 
    "keterangan_khusus": "suka nonton upin ipin", 
    "ras": "ayam malaysia", 
    "gambar": "https://www.putraperkasa.co.id/wp-content/uploads/2023/11/Ayam-New-Hampshire-001.webp",
    "pemilikId": 2
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/daftarhewan/1

###
DELETE http://localhost:5000/logout
