GET http://localhost:5000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbmt5dXQxMjMiLCJpYXQiOjE3NDgxODI2NjIsImV4cCI6MTc0ODE4MzU2Mn0.URvU63ft1lJ85FtqJy43DvlzOkrKmIzOcO2EgxhqWeI

###
POST http://localhost:5000/user
Content-Type: application/json 
Authorization: Bearer <your_access_token>

{
    "username": "adminkyut123", 
    "password": "12345"  
}

###
POST http://localhost:5000/login
Content-Type: application/json 
Authorization: Bearer <your_access_token>

{
    "username": "adminkyut123", 
    "password": "12345"  
}

###
POST http://localhost:5000/daftarhewan
Content-Type: application/json 
Authorization: Bearer <your_access_token>

{
    "nama_hewan": "ayam", 
    "bobot_hewan": 15, 
    "keterangan_khusus": "makanan harus fresh", 
    "ras": "ayam petelur", 
    "gambar": "https://www.putraperkasa.co.id/wp-content/uploads/2023/11/Ayam-New-Hampshire-001.webp"
}

###
PUT http://localhost:5000/daftarhewan/2
Content-Type: application/json 
Authorization: Bearer <your_access_token>

{
    "nama_hewan": "si imhut", 
    "bobot_hewan": 15, 
    "keterangan_khusus": "suka nonton upin ipin", 
    "ras": "ayam malaysia", 
    "gambar": "https://www.putraperkasa.co.id/wp-content/uploads/2023/11/Ayam-New-Hampshire-001.webp"
}

###
POST http://localhost:5000/daftarpemilik
Content-Type: application/json 
Authorization: Bearer <your_access_token>

{
    "nama_pemilik": "dapid", 
    "no_hp": "08123456789", 
    "alamat": "sewon", 
    "email": "dapid@gmail.com"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout